# Generated by Django 5.2.8 on 2025-11-26 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklist',
            old_name='Task',
            new_name='task',
        ),
    ]
